version: '3.8'

services:
  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data 
    command: ["python", "main.py", "--videos_dir", "/app/data/videos", "--mount", "/app/data/models", "--save_dir", "/app/data/predictions"]
